// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }







import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pop-a-Pixel',
  description: 'A fun whack-a-mole style game. Test your reflexes and beat your high score!',
  openGraph: {
    title: 'Pop-a-Pixel',
    description: 'A fun whack-a-mole style game. Test your reflexes and beat your high score!',
    url: 'https://pop-a-pixel.example.com',
    siteName: 'Pop-a-Pixel',
    images: [
      {
        url: 'https://www.google.com/imgres?q=pop%20a%20pixel%20game%20picture&imgurl=https%3A%2F%2Fimg.itch.zone%2FaW1nLzE1Nzg2NzQ0LnBuZw%3D%3D%2F315x250%2523c%2FIW2%252Bo8.png&imgrefurl=https%3A%2F%2Fitch.io%2Fgames%2Fnew-and-popular%2Fgenre-simulation%2Fstore%2Ftag-pixel-art%3Fpage%3D2&docid=ZPLzurZ7l323TM&tbnid=jVKMH7cSZ-_QsM&vet=12ahUKEwjWqImBgKqKAxWTSPEDHU4BFC8QM3oECFMQAA..i&w=315&h=250&hcb=2&itg=1&ved=2ahUKEwjWqImBgKqKAxWTSPEDHU4BFC8QM3oECFMQAA',
        width: 1200,
        height: 630,
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Pop-a-Pixel',
    description: 'A fun whack-a-mole style game. Test your reflexes and beat your high score!',
    images: ['https://pop-a-pixel.example.com/twitter-image.png'],
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen bg-gradient-to-b from-blue-100 to-blue-200`}>
        {children}
      </body>
    </html>
  )
}

